version: '3'
services:
  sql:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./.mysql-data:/var/lib/mysql/
  crawler:
    build:
      context: './docker-base'
    depends_on:
      - sql
    ports:
      - "80:80"
    volumes:
      - ./scrap-json:/scrap/json:rw
      - ./scrap-torrent:/scrap/torrent:rw
      - ./media/img:/static/img:rw
      - ./media/film:/static/film:rw
      - ./media/film/detail:/static/film/detail:rw
      - ./media/film/download:/static/film/download:rw
      - ./code:/code
      - ./logs:/LOGS